#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


# Wait for Django migrations to complete before starting beat.
until python /app/manage.py migrate --check > /dev/null 2>&1; do
    >&2 echo "Waiting for database migrations to complete..."
    sleep 3
done

exec celery -A config.celery_app beat -l INFO
