# Generated by Django 6.0.8 on 2026-08-22 00:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('committees', '0004_committeecapability'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflows', to='contenttypes.contenttype', verbose_name='Content Type')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_workflows', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_initial', models.BooleanField(default=False, verbose_name='Initial')),
                ('is_terminal', models.BooleanField(default=False, verbose_name='Terminal')),
                ('review_committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_review_states', to='committees.committee', verbose_name='Review Committee')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='workflows.workflow', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Workflow State',
                'verbose_name_plural': 'Workflow States',
                'ordering': ['workflow', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(verbose_name='Object ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflows.workflow', verbose_name='Workflow')),
                ('current_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflows.workflowstate', verbose_name='Current State')),
            ],
            options={
                'verbose_name': 'Workflow Instance',
                'verbose_name_plural': 'Workflow Instances',
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='workflows.workflowstate', verbose_name='Source')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='workflows.workflowstate', verbose_name='Target')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workflows.workflow', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Workflow Transition',
                'verbose_name_plural': 'Workflow Transitions',
                'ordering': ['workflow', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransitionAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('set_update_status', 'Set Budget Status'), ('set_budget_approver', 'Set Budget Approver'), ('clear_budget_approver', 'Clear Budget Approver')], max_length=50, verbose_name='Action Type')),
                ('value', models.CharField(blank=True, max_length=100, verbose_name='Value')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('transition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='workflows.workflowtransition', verbose_name='Transition')),
            ],
            options={
                'verbose_name': 'Workflow Transition Action',
                'verbose_name_plural': 'Workflow Transition Actions',
                'ordering': ['transition', 'order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransitionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_transitions_made', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workflows.workflowstate', verbose_name='From State')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transation_logs', to='workflows.workflowinstance', verbose_name='Workflow Instance')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workflows.workflowstate', verbose_name='To State')),
                ('transition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='workflows.workflowtransition', verbose_name='Transition')),
            ],
            options={
                'verbose_name': 'Workflow Transition Log',
                'verbose_name_plural': 'Workflow Transition Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransitionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('authorization_type', models.CharField(choices=[('requester', 'Requester'), ('capability', 'Committee Capability'), ('committee_member', 'Committee Member'), ('committee_leader', 'Committee Leader'), ('presidential_office_leader', 'Presidential Office Leader')], max_length=50, verbose_name='Authorization Type')),
                ('capabiltity', models.CharField(blank=True, max_length=50, verbose_name='Capability')),
                ('committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_authorization_rules', to='committees.committee', verbose_name='Committee')),
                ('transition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='workflows.workflowtransition', verbose_name='Transition')),
            ],
            options={
                'verbose_name': 'Workflow Transition Rule',
                'verbose_name_plural': 'Workflow Transition Rules',
            },
        ),
        migrations.AddConstraint(
            model_name='workflowstate',
            constraint=models.UniqueConstraint(fields=('workflow', 'name'), name='unique_workflow_state_name'),
        ),
        migrations.AddConstraint(
            model_name='workflowinstance',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id'), name='unique_workflow_instance_per_object'),
        ),
    ]
