# Generated by Django 6.0.8 on 2026-08-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowtransitionrule',
            name='capabiltity',
        ),
        migrations.AddField(
            model_name='workflowtransitionrule',
            name='capability',
            field=models.CharField(blank=True, choices=[('treasury', 'Treasury / Budget Approval'), ('event_creation', 'Event Creation')], max_length=50, verbose_name='Capability'),
        ),
    ]
