#!/bin/bash

set -o errexit
set -o nounset


# Wait for Django migrations to complete before starting the worker.
until python manage.py migrate --check > /dev/null 2>&1; do
    >&2 echo "Waiting for database migrations to complete..."
    sleep 3
done

exec watchfiles --filter python celery.__main__.main --args '-A config.celery_app worker -l INFO'
