# Generated by Django 6.0.8 on 2026-08-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestescalation',
            name='request',
        ),
        migrations.RemoveField(
            model_name='requestassignmenthistory',
            name='request',
        ),
        migrations.RemoveField(
            model_name='requeststatetransition',
            name='request',
        ),
        migrations.RemoveField(
            model_name='requestassignmenthistory',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='requestassignmenthistory',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='requestescalation',
            name='handled_by',
        ),
        migrations.RemoveField(
            model_name='requestescalation',
            name='raised_by',
        ),
        migrations.RemoveField(
            model_name='requeststatetransition',
            name='actor',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.JSONField(blank=True, default=dict, verbose_name='Description'),
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='RequestAssignmentHistory',
        ),
        migrations.DeleteModel(
            name='RequestEscalation',
        ),
        migrations.DeleteModel(
            name='RequestStateTransition',
        ),
    ]
