# Generated by Django 6.0.8 on 2026-08-20 00:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0003_committee_is_presidential_office'),
        ('events', '0002_remove_requestescalation_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='status',
            field=models.CharField(default='Pending', max_length=50, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='event',
            name='current_state',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending Treasurer Review', 'Pending Treasurer Review'), ('Pending Presidential Review', 'Pending Presidential Review'), ('Budget Approved', 'Budget Approved'), ('Active', 'Active'), ('Completed', 'Completed'), ('Budget Rejected', 'Budget Rejected'), ('Turned Down', 'Turned Down')], default='Draft', max_length=50, verbose_name='Current State'),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.CreateModel(
            name='TreasuryCommittee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added At')),
                ('committee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treasury_designation', to='committees.committee', verbose_name='Treasury Committee')),
            ],
            options={
                'verbose_name': 'Treasury Committee',
                'verbose_name_plural': 'Treasury Committees',
            },
        ),
    ]
