# Generated by Django 6.0.8 on 2026-08-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_budget_status_alter_event_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TreasuryCommittee',
        ),
    ]
