# Generated by Django 6.0.8 on 2026-08-22 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_delete_treasurycommittee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='current_state',
        ),
        migrations.DeleteModel(
            name='EventStateTransition',
        ),
    ]
