# Generated by Django 6.0.8 on 2026-08-17 00:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Committee',
                'verbose_name_plural': 'Committees',
            },
        ),
        migrations.CreateModel(
            name='CommitteeRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Order')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='committees.committee', verbose_name='Committee')),
            ],
            options={
                'verbose_name': 'Committee Role',
                'verbose_name_plural': 'Committee Roles',
                'ordering': ['committee', 'order'],
                'unique_together': {('committee', 'name')},
            },
        ),
    ]
