# Generated by Django 6.0.8 on 2026-08-17 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_committees', to=settings.AUTH_USER_MODEL, verbose_name='Director'),
        ),
        migrations.AddField(
            model_name='committee',
            name='vice_director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice_directed_committees', to=settings.AUTH_USER_MODEL, verbose_name='Vice Director'),
        ),
    ]
