# Generated by Django 6.0.8 on 2026-08-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0002_committee_director_committee_vice_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='is_presidential_office',
            field=models.BooleanField(default=False, verbose_name='Is Presidential Office'),
        ),
    ]
