# Generated by Django 6.0.8 on 2026-08-20 13:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0003_committee_is_presidential_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('capability', models.CharField(choices=[('treasury', 'Treasury / Budget Approval'), ('event_creation', 'Event Creation')], max_length=50, verbose_name='Capability')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added At')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='committees.committee', verbose_name='Committee')),
            ],
            options={
                'verbose_name': 'Committee Capability',
                'verbose_name_plural': 'Committee Capabilities',
                'unique_together': {('committee', 'capability')},
            },
        ),
    ]
